src/Entity/Request.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\RequestRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RequestRepository::class)
 */
class Request
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $requested_at = null;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $responded_at = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $payload = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $method = null;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $response_code = 200;

    /**
     * @return int|null
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRequestedAt(): ?DateTimeInterface
    {
        return $this->requested_at;
    }

    public function setRequestedAt(DateTimeInterface $requested_at): self
    {
        $this->requested_at = $requested_at;

        return $this;
    }

    public function getRespondedAt(): ?DateTimeInterface
    {
        return $this->responded_at;
    }

    public function setRespondedAt(?DateTimeInterface $responded_at): self
    {
        $this->responded_at = $responded_at;

        return $this;
    }

    public function getPayload(): ?string
    {
        return $this->payload;
    }

    public function setPayload(?string $payload): self
    {
        $this->payload = $payload;
        return $this;
    }

    public function getMethod(): ?string
    {
        return $this->method;
    }

    public function setMethod(string $method): self
    {
        $this->method = $method;

        return $this;
    }

    public function getResponseCode(): ?int
    {
        return $this->response_code;
    }

    public function setResponseCode(?int $response_code): self
    {
        $this->response_code = $response_code;

        return $this;
    }
}

templates/auth.html.twig
{% apply spaceless %}
    <!DOCTYPE html>
    <html lang="{{ app.request.locale }}" class="js">
    <head>
        <meta charset="utf-8">
        <meta name="author" content="devscast">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <link rel="shortcut icon" href="./images/favicon.png">

        <title>{% block title %}Authentification{% endblock %} | EsisHoraireBot</title>
        {{ encore_entry_link_tags('app') }}
    </head>

    <body class="nk-body bg-white npc-default pg-auth">
    <div class="nk-app-root">
        <div class="nk-main ">
            <div class="nk-wrap nk-wrap-nosidebar">
                <div class="nk-content ">
                    <div class="nk-split nk-split-page nk-split-md">
                        <div class="nk-split-content nk-block-area nk-block-area-column nk-auth-container bg-white">
                            <div class="nk-block nk-block-middle nk-auth-body">
                                <div class="brand-logo pb-5">
                                    <a href="#" class="logo-link">
                                        <img class="logo-img logo-img-lg" src="https://www.esisalama.com/assets/img/logo.png" alt="logo">
                                    </a>
                                </div>
                                {% block body %}{% endblock %}
                            </div>
                        </div>
                        <div class="nk-split-content nk-split-stretch bg-abstract" style="background-image: url('https://images.pexels.com/photos/3059748/pexels-photo-3059748.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
    </html>
{% endapply %}

templates/broadcast.html.twig
{% extends '_layout/base.html.twig' %}

{% block section %}
    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Message Broadcast</h3>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-bordered">
        <div class="card-inner">
            {{ form_start(form) }}
                {{ form_widget(form) }}
                <button type="submit" class="btn btn-primary">Envoyer</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/command.html.twig
{% extends '_layout/base.html.twig' %}

{% block section %}
    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Commandes</h3>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-bordered">
        <div class="card-inner-group">
            <div class="card-inner">
                <div class="between-center flex-wrap g-3">
                    <div class="nk-block-text"><h6>bot fetch-timetable</h6>
                        <p>Récupérer les tables de temps et les mettre en cache sur le serveur.</p>
                    </div>
                    <div class="nk-block-actions flex-shrink-sm-0">
                        <div class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                            <button data-command-button data-url="{{ path('app_command_execute', {command: 'bot:fetch-timetable'}) }}" class="btn btn-primary">
                                exécuter
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-inner">
                <div class="between-center flex-wrap g-3">
                    <div class="nk-block-text"><h6>bot telegram-push</h6>
                        <p>Envoyer l'horaire aux utilisateurs abonnés</p>
                    </div>
                    <div class="nk-block-actions flex-shrink-sm-0">
                        <div class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                            <button data-command-button data-url="{{ path('app_command_execute', {command: 'bot:telegram-push'}) }}" class="btn btn-primary">
                                exécuter
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-inner">
                <div class="between-center flex-wrap g-3">
                    <div class="nk-block-text"><h6>bot web-scrape</h6>
                        <p>Récupérer les pages de la table horaire et les mettre en cache sur le serveur.</p>
                    </div>
                    <div class="nk-block-actions flex-shrink-sm-0">
                        <div class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                            <button data-command-button data-url="{{ path('app_command_execute', {command: 'bot:web-scrape'}) }}" class="btn btn-primary">
                                exécuter
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-inner">
                <div class="between-center flex-wrap g-3">
                    <div class="nk-block-text"><h6>bot telegram-webhook</h6>
                        <p>Configurer un webhook pour le robot telegram</p>
                    </div>
                    <div class="nk-block-actions flex-shrink-sm-0">
                        <div class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                            <button disabled data-command-button data-url="{{ path('app_command_execute', {command: 'bot:telegram-webhook'}) }}" class="btn btn-primary">
                                exécuter
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html.twig
{% extends '_layout/base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>
{% endblock %}

{% block section %}
    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Statistiques</h3>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="row mb-5">
        <div class="col-12 col-md-4 mg-b-10 mg-t-10 mg-sm-t-0">
            <div class="card card-body">
                <h6 class="tx-uppercase tx-11 tx-spacing-1 tx-color-02 tx-bold mg-b-10">
                    Aujourd'hui
                </h6>
                <div class="d-flex d-lg-block d-xl-flex align-items-end">
                    <h3 class="tx-bold tx-rubik mg-b-10 mg-r-5 lh-1">{{ days }} </h3>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 mg-b-10 mg-t-10 mg-sm-t-0">
            <div class="card card-body">
                <h6 class="tx-uppercase tx-11 tx-spacing-1 tx-color-02 tx-bold mg-b-10">
                    7 derniers jours
                </h6>
                <div class="d-flex d-lg-block d-xl-flex align-items-end">
                    <h3 class="tx-bold tx-rubik mg-b-10 mg-r-5 lh-1">{{ weeks }} </h3>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 mg-b-10 mg-t-10 mg-sm-t-0">
            <div class="card card-body">
                <h6 class="tx-uppercase tx-11 tx-spacing-1 tx-color-02 tx-bold mg-b-10">
                    30 derniers jours
                </h6>
                <div class="d-flex d-lg-block d-xl-flex align-items-end">
                    <h3 class="tx-bold tx-rubik mg-b-10 mg-r-5 lh-1">{{ months }} </h3>
                </div>
            </div>
        </div>
    </div>

    <div class="card card-preview">
        <table class="table table-orders">
            <thead class="tb-odr-head">
            <tr class="tb-odr-item">
                <th>ID</th>
                <th>Méthode</th>
                <th>Date</th>
                <th>Demande</th>
                <th>Réponse</th>
                <th>Code Réponse</th>
                <th class="tb-odr-action">&nbsp;</th>
            </tr>
            </thead>
            <tbody class="tb-odr-body">
            {% for item in items %}
                <tr class="tb-odr-item">
                    <td>{{ item.id }}</td>
                    <td>{{ item.method }}</td>
                    <td class="fw-bolder">{{ item.requestedAt | date('d M Y') }}</td>
                    <td>{{ item.requestedAt | date('H:i:s') }}</td>
                    <td>{{ item.respondedAt | date('H:i:s') }}</td>
                    <td class="fw-bolder">{{ item.responseCode }}</td>
                    {% if item.payload %}
                        <td class="tb-odr-action">
                            <div class="tb-odr-btns d-none d-md-inline">
                                <button data-create-button data-toggle="modal" data-target="#modal_{{ item.id }}"
                                        class="btn btn-sm btn-dim btn-primary">Payload
                                </button>
                            </div>
                        </td>
                        {{ include('_includes/_modal.html.twig', {id: "modal_" ~ item.id, title: 'Payload', body: item.payload}) }}
                    {% else %}
                        <td>&nbsp;</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="mt-5 d-flex align-center justify-center">
        {{ knp_pagination_render(items) }}
    </div>
{% endblock %}