src/Entity/Subscription.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\SubscriptionRepository;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use TelegramBot\Api\Types\Message;

/**
 * @ORM\Entity(repositoryClass=SubscriptionRepository::class)
 */
class Subscription
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $name = null;

    /**
     * @ORM\Column(type="integer", unique=true)
     */
    private ?int $chat_id = null;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private ?string $promotion = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $created_at = null;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     */
    private ?bool $is_active = true;

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getChatId(): ?int
    {
        return $this->chat_id;
    }

    public function setChatId(int $chat_id): self
    {
        $this->chat_id = $chat_id;

        return $this;
    }

    public function getPromotion(): ?string
    {
        return $this->promotion;
    }

    public function setPromotion(string $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public static function fromMessageCommand(Message $message, string $promotion): self
    {
        return (new Subscription())
            ->setName($message->getChat()->getUsername() ?: '')
            ->setPromotion($promotion)
            ->setChatId($message->getChat()->getId())
            ->setIsActive(true);
    }
}

src/Form/SubscriptionType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Subscription;
use App\Repository\PromotionRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class SubscriptionType
 * @package App\Form
 * @author bernard-ng <ngandubernard@gmail.com>
 */
class SubscriptionType extends AbstractType
{
    public function __construct(private PromotionRepository $repository)
    {
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nom'])
            ->add('chat_id', TextType::class, ['label' => 'Chat ID'])
            ->add('promotion', ChoiceType::class, [
                'choices' => $this->repository->getPromotionChoiceList()
            ])
            ->add('is_active', CheckboxType::class, ['label' => 'Abonnement actif']);
    }

    /**
     * @param OptionsResolver $resolver
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Subscription::class,
        ]);
    }
}

src/Controller/SubscriptionController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Subscription;
use App\Form\SubscriptionType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 * Class SubscriptionController
 * @package App\Controller
 * @author bernard-ng <ngandubernard@gmail.com>
 */
class SubscriptionController extends CRUDController
{
    protected string $entity = Subscription::class;
    protected string $form = SubscriptionType::class;
    protected const FILTERABLE_FIELDS = [];
    protected array $route = [
        'index' => 'app_subscription_index',
        'new' => 'app_subscription_new',
        'edit' => 'app_subscription_edit',
        'delete' => 'app_subscription_delete'
    ];
    protected array $views = [
        'index' => 'subscription/index.html.twig',
        'new' => 'subscription/new.html.twig',
        'edit' => 'subscription/edit.html.twig',
        'form' => "_includes/_forms.html.twig"
    ];

    public function index(Request $request): Response
    {
        return $this->crudIndex($request);
    }

    public function new(Request $request): Response
    {
        return $this->crudNew($request);
    }

    public function edit(Request $request, Subscription $item): Response
    {
        return $this->crudEdit($item, $request);
    }

    public function delete(Request $request, Subscription $item): Response
    {
        return $this->crudDelete($item, $request);
    }
}

templates/subscription/index.html.twig
{% extends '_layout/base.html.twig' %}

{% block section %}
    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Abonnements</h3>
            </div>
            <div class="nk-block-head-content">
                <div class="toggle-wrap nk-block-tools-toggle">
                    <div class="toggle-expand-content" data-content="more-options">
                        <ul class="nk-block-tools g-3">
                            <li class="nk-block-tools-opt">
                                <a href="#" class="btn btn-icon btn-primary d-md-none">
                                    <em class="icon ni ni-plus"></em>
                                </a>
                                <a href="#" title="Ajouter"
                                   data-create-button
                                   data-url="{{ path('app_subscription_new') }}"
                                   data-toggle="modal"
                                   data-target="#modal" class="btn btn-primary d-none d-md-inline-flex">
                                    <em class="icon ni ni-plus"></em><span>Ajouter</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                {{ include('_includes/_modal.html.twig', {id: 'modal', title: 'Ajouter Subscription'}) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-preview">
        <table class="table table-orders">
            <thead class="tb-odr-head">
            <tr class="tb-odr-item">
                <th>Chat ID</th>
                <th>Promotion</th>
                <th>Nom</th>
                <th>Date</th>
                <th>Actif</th>
                <th class="tb-odr-action">&nbsp;</th>
            </tr>
            </thead>
            <tbody class="tb-odr-body">
                {% for item in items %}
                    <tr class="tb-odr-item">
                        <td><a target="_blank" href="https://t.me/{{ item.name }}">{{ item.chatId }}</a></td>
                        <td class="fw-bolder">{{ item.promotion }}</td>
                        <td class="fw-bolder">{{ item.name }}</td>
                        <td>{{ item.createdAt | date }}</td>
                        <td>
                           {% if item.active == 1 %}
                               <span class="badge badge-sm badge-dot badge-success">Actif</span>
                           {% else %}
                               <span class="badge badge-sm badge-dot badge-danger">Inactif</span>
                           {% endif %}
                        </td>
                        <td class="tb-odr-action">
                            <div class="tb-odr-btns d-none d-md-inline">
                                <a href="#" title="Ajouter"
                                   data-create-button
                                   data-url="{{ path('app_subscription_edit', {id: item.id}) }}"
                                   data-toggle="modal"
                                   data-target="#subscription_{{ item.id }}" class="btn btn-dim btn-primary d-none d-md-inline-flex">
                                    <span>Éditer</span>
                                </a>
                            </div>
                        </td>
                        {{ include('_includes/_modal.html.twig', {id: "subscription_#{ item.id }", title: 'Éditer Subscription'}) }}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="mt-5 d-flex align-center justify-center">
        {{ knp_pagination_render(items) }}
    </div>
{% endblock %}